lib/report_web/router.ex
defmodule ReportWeb.Router do
  use ReportWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(Report.Auth.Pipeline)
    plug(Report.Auth.CurrentUser)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  scope "/", ReportWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", SessionController, :index)
    post("/login", SessionController, :login)

    get("/logout", SessionController, :logout)
  end

  scope "/", ReportWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    get("/overview", RecordOfActivitiesController, :index)
    get("/records", RecordOfActivitiesController, :list)
    post("/records", RecordOfActivitiesController, :create)
    get("/records/new", RecordOfActivitiesController, :new)
    get("/records/export", RecordOfActivitiesController, :export)

    post("/entry/create", EntryController, :create)

    get("/masterdata", RecordOfActivitiesController, :master_data)
  end
end

lib/report_web/views/layout_view.ex
defmodule ReportWeb.LayoutView do
  use ReportWeb, :view
end

lib/report_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PN DataSecure - Verarbeitungsverzeichnis</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= if @conn.request_path != record_of_activities_path(@conn, :new) do %>
      <div class="fixed-action-btn">
        <%= link(to: record_of_activities_path(@conn, :new), class: "btn-floating btn-large amber",  id: "add-entry") do %>
          <i class="large material-icons">add</i>
        <% end %>
      </div>
    <% end %>

  <header>
    <nav class="nav-extended teal darken-3">
      <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <a href="/" class="brand-logo">Verarbeitungsverzeichnis</a>
      </div>
      <div class="nav-content">
        <h5 class="title"><%= assigns[:page_title] || "NO TITLE" %></h5>
      </div>

    </nav>
  </header>

    <ul id="slide-out" class="sidenav sidenav-fixed blue-grey darken-3">
      <li>
        <div class="user-view">
          <div class="background">
            <img class="background-logo" src="<%= static_path(@conn, "/images/header-logo.png") %>">
          </div>
          <span class="white-text name">
            <%= @current_user.prename <> " " <> @current_user.name %>
          </span>
          <span class="white-text email">
            <%= @current_company.name %>
          </span>
        </div>
      </li>
      <li>
        <a class="blue-grey-text text-lighten-3 subheader">
          Allgemeines
        </a>
      </li>
      <li>
        <%= link to: session_path(@conn, :index), class: "white-text" do %>
          Übersicht
          <i class="white-text material-icons">dashboard</i>
        <% end %>
      </li>
       <li>
        <%= link to: record_of_activities_path(@conn, :master_data), class: "white-text" do %>
          Stammdaten
          <i class="white-text material-icons">assignment_ind</i>
        <% end %>
      </li>
      <li>
        <a class="white-text">
          Mitarbeiter
          <i class="white-text material-icons">group</i>
        </a>
      </li>
      <li>
        <a class="white-text">
          Abteilungen
          <i class="white-text material-icons">domain</i>
        </a>
      </li>
      <li>
        <div class="divider"></div>
      </li>
      <li>
        <a class="blue-grey-text text-lighten-3 subheader">
          Verzeichnis für Verantwortliche
        </a>
      </li>
      <li>
        <%= link to: record_of_activities_path(@conn, :list), class: "white-text" do %>
          Einträge anzeigen
          <i class="white-text material-icons">view_list</i>
        <% end %>
      </li>
      <li>
        <%= link to: record_of_activities_path(@conn, :export), class: "white-text" do %>
          Verzeichnis exportieren
          <i class="white-text material-icons">file_download</i>
        <% end %>
      </li>
      <li class="settings">
        <a class="white-text">
          Einstellungen
          <i class="white-text material-icons">settings</i>
        </a>
      </li>
      <li class="logout">
        <a href="/logout" class="white-text">
        Abmelden
          <i class="white-text material-icons">lock</i>
        </a>
      </li>
    </ul>
    <%# <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a> %>

    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <div class="tap-target teal darken-4" data-target="add-entry">
      <div class="tap-target-content">
        <h5 class="white-text">Eintrag erstellen</h5>
        <p class="white-text">Hier klicken, um dem Verarbeitungsverzeichnis einen neuen Eintrag hinzuzufügen</p>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/report_web/templates/layout/login_layout.html.eex
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Report!</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="login-wrapper">
      <%= render @view_module, @view_template, assigns %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>